// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw_MQmh0-bDeaFxkaj2wmcs6onmryXXCw',
    appId: '1:79044649135:web:9a2c8c32d2469297e9745a',
    messagingSenderId: '79044649135',
    projectId: 'dapurkasih',
    authDomain: 'dapurkasih.firebaseapp.com',
    storageBucket: 'dapurkasih.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhBmX3bzWawyfNsI9BqoULVdO8z1DtmxM',
    appId: '1:79044649135:android:edcb0336ae533df7e9745a',
    messagingSenderId: '79044649135',
    projectId: 'dapurkasih',
    storageBucket: 'dapurkasih.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk1Zz8PHPNjMicGNUPMyVsTgXKaEDyqgo',
    appId: '1:79044649135:ios:691ac48f0fea1ed8e9745a',
    messagingSenderId: '79044649135',
    projectId: 'dapurkasih',
    storageBucket: 'dapurkasih.firebasestorage.app',
    iosBundleId: 'com.example.dapur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk1Zz8PHPNjMicGNUPMyVsTgXKaEDyqgo',
    appId: '1:79044649135:ios:691ac48f0fea1ed8e9745a',
    messagingSenderId: '79044649135',
    projectId: 'dapurkasih',
    storageBucket: 'dapurkasih.firebasestorage.app',
    iosBundleId: 'com.example.dapur',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw_MQmh0-bDeaFxkaj2wmcs6onmryXXCw',
    appId: '1:79044649135:web:6ff0a11328eb65e3e9745a',
    messagingSenderId: '79044649135',
    projectId: 'dapurkasih',
    authDomain: 'dapurkasih.firebaseapp.com',
    storageBucket: 'dapurkasih.firebasestorage.app',
  );
}
